### ISSUE TITLE
Crashes right after launch.

### ISSUE THREAD

**Issue by DumpsterJ** [JamesCJ60/Playmate-Game-Launcher#1]
Crashes shortly after launch. Tried to launch as admin. Made no difference. Using on AYANEO 2 Win 11 16gb 1tb model.

**Comment by JamesCJ60** [comment]
Hi, I’m aware of the issue and a fix will be uploaded shortly

**Comment by DumpsterJ** [comment]
Awesome. When you upload it I will try again :) . Thank you.

**Comment by DumpsterJ** [comment]
Thank you! I will try the new version soon !
